import{a as P,S as v,i as a}from"./assets/vendor-CIF6YjI2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="https://pixabay.com/api/",q="40538003-a69e71f72cedcb2a8af9fb674";async function d(t,o){const s={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await P.get(E,{params:s})).data}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:i,comments:S,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info-block">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${i}</span></p>
        <p class="info-item"><b>Comments</b><span>${S}</span></p>
        <p class="info-item"><b>Downloads</b><span>${w}</span></p>
      </div>
    </li>
  `).join("");u.insertAdjacentHTML("beforeend",o),$.refresh()}function R(){u.innerHTML=""}function h(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function y(){f.classList.remove("is-hidden")}function b(){f.classList.add("is-hidden")}const M=document.querySelector(".form"),B=document.querySelector(".load-more-btn");let l="",c=1;const L=15;M.addEventListener("submit",I);B.addEventListener("click",O);async function I(t){t.preventDefault();const o=t.currentTarget;if(l=o.elements.searchQuery.value.trim(),l===""){a.warning({title:"Warning",message:"Please enter a search keyword!",position:"topRight"});return}c=1,R(),b(),h();try{const s=await d(l,c);if(s.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(s.hits),s.totalHits>L?y():a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){a.error({title:"Failure",message:`Something went wrong: ${s.message}`,position:"topRight"})}finally{g(),o.reset()}}async function O(){c+=1,b(),h();try{const t=await d(l,c);p(t.hits),C(),c*L>=t.totalHits?a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch(t){a.error({title:"Error",message:`Failed to fetch more images: ${t.message}`,position:"topRight"})}finally{g()}}function C(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
